### ISSUE TITLE
Application fails to launch

### ISSUE THREAD

**Issue by johnstephens** [laffra/happymac#10]
Opening it by clicking on the app icon fails silently, but attempting to launch it from the terminal (`open -a happymac` in Darwin) reliably produces the following error message:

```      
LSOpenURLsWithRole() failed for the application /Applications/happymac.app with error -10810.
```
Same behavior whether I install the application using Homebrew or by the disk image downloaded from http://chrislaffra.com/happymac/happymac.dmg

Cheers!

**Comment by laffra** [comment]
Can you try something? In a command shell, run this:

`git clone https://github.com/laffra/happymac.git && cd happymac && ./install.sh && python src/happymac.py`

I wonder if we get a better error message then?

**Comment by johnstephens** [comment]
Thank you, @laffra! I ran that command, and the STDOUT was a lot more than you probably want to see.

There was an error when it tried to install Quartz via Homebrew:

```
Collecting quartz
  Downloading quartz-0.0.1.dev0.tar.gz (217 kB)
     |████████████████████████████████| 217 kB 2.3 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/81/35yq9pz95_73_9y_t01hdybr0000gn/T/pip-download-ssf8f5/quartz/setup.py'"'"'; __file__='"'"'/private/var/folders/81/35yq9pz95_73_9y_t01hdybr0000gn/T/pip-download-ssf8f5/quartz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/81/35yq9pz95_73_9y_t01hdybr0000gn/T/pip-pip-egg-info-YCw_nq
         cwd: /private/var/folders/81/35yq9pz95_73_9y_t01hdybr0000gn/T/pip-download-ssf8f5/quartz/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/81/35yq9pz95_73_9y_t01hdybr0000gn/T/pip-download-ssf8f5/quartz/setup.py", line 35, in <module>
        install_requires=read_dependencies("requirements.txt"),
      File "/private/var/folders/81/35yq9pz95_73_9y_t01hdybr0000gn/T/pip-download-ssf8f5/quartz/setup.py", line 7, in read_dependencies
        with open(req_file) as req:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by laffra** [comment]
You should still be able to run from the command line, even with this error
happening.
Can you run `python src/happymac.py` and see what happens?

**Comment by johnstephens** [comment]
Thanks again, @laffra! This seems like progress. When I launch it from the command line like this, I briefly see an emoji in the task bar, and the terminal displays the following output when it crashes:

```
2020-10-31 14:06:42.222940: Find version v00001 
2020-10-31 14:06:42.223286: Downloads: Could not find version v00001 in /Users/john/HappyMacApp/downloads/v00001 
2020-10-31 14:06:42.223439: Calling run on <module 'versions.v00001.main' from '/Users/john/Desktop/happymac/src/versions/v00001/main.pyc'> 
2020-10-31 14:06:42.272690: Started HappyMac v00001 
'NoneType' object has no attribute 'power_plugged'
```

**Comment by johnstephens** [comment]
I got the the app to launch and remain open by commenting out the end of the return statement on line 23 of src/versions/v00001/process.py:

```
    return #not psutil.sensors_battery().power_plugged
```

I'm guessing this threw an error because I ran running it on an iMac, rather than a laptop?

**Comment by laffra** [comment]
This is a great analysis. I never knew on iMac this API would fail. Do you
want to send a PR?

**Comment by johnstephens** [comment]
Sure, but I'm not sure what the `on_battery()` function does in the code. I see it referenced in suspender.py in the `manage()` and `suspend_process()` functions. What are the implications of having `on_battery()` simply "return"—without a boolean value?

My first thought would be, first test whether "sensors_battery()" exists, so that the purpose of this function may be served when the API supports it. But I don't know the API at all to integrate that into a PR.

**Comment by laffra** [comment]
No problem. I will take a look. Thanks for doing the investigation. Very
helpful.

**Comment by johnstephens** [comment]
I am very happy to help if I can, I just don't want to impose on you the cost of getting me "up to speed".

**Comment by laffra** [comment]
Understood. I have not looked at this code myself in a long time, so it may
look as new to me as it does to you 😉.

**Comment by laffra** [comment]
@johnstephens This should now be fixed in v00025. If you restart HappyMac it should auto-update and work better on iMac's. I do not have access to an iMac, so I could not do a conclusive test, so I would be happy if you can share your experience with the latest version.

**Comment by laffra** [comment]
The fix is in [this line](https://github.com/laffra/happymac/blob/d1df2c8b1665825f93d42bde99219d2e37e18fe3/src/versions/v00001/process.py#L26).

**Comment by johnstephens** [comment]
Yes, that fixes it for me! Thank you, @laffra!

I tried installing the new version via Homebrew and then the Disk Image installer, and they didn't launch. I'm guessing that those haven't been updated yet. Cloning the repository and running it from the command line worked perfectly.
