### ISSUE TITLE
Add to homebrew cask?

### ISSUE THREAD

**Issue by uber-mahyar2** [laffra/happymac#7]
It would be nice to run `homebrew cask install happymac` to install this app.

You could also use github releases functionality to host the dmg file for homebrew.

**Comment by laffra** [comment]
Nice idea. Will look into this.

**Comment by ollietreend** [comment]
It looks like this is now available as of Homebrew/homebrew-cask#90038.

More info: https://formulae.brew.sh/cask/happymac

Install with: `brew cask install happymac`

**Comment by laffra** [comment]
Interesting. Thanks for letting me know.

**Comment by laffra** [comment]
Is now available on brew
